spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: admin
    password: admin
    driver-class-name: com.mysql.jdbc.Driver