spring:
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  datasource:
    url: jdbc:mysql://localhost:3306/library?createDatabaseIfNotExist=true
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Springs Fox 3.0.0 nsot supporting new P2athPattern Based Path Matching Strategy for Spring MVC which is now the new default from spring-boot 2.6.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: update